version: 3

services:
  get5-web:
    build: docker/Dockerfile
    ports:
      - "8080:80"
  
  mariadb:
    image: bitnami/mariadb:10.5-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155
    volumes:
      - data:/bitnami/mariadb/data
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      
volumes:
  data:
    driver: local
